[[ 1123 ]]
  1630 = [
    { title = 'some todos' }
    { todos  }
  ]
	  # i spent all this fucking time doing nothing all the time
    todos:
      -[ ] write in one file

    ]
    content: """
    i just wanna type
	  am i writing too much?
    shouldnt i just be writing all my blogshit in one file?
		  isnt that the whole point of rd?"""
	im so confused

i need some hotkeys

-[ ]  hotkeys


# 1700
  need to work on alot of stuffs

# 1711
  this is why we just learn how to type faster
  
  this is supposed to be some type of idea board right?

-[?] toml

# 1744 =
  big nope to .toml

-[ ] shift focus to the blog

# 1753
-[ ] write a script to functionally process this

-[ ] trackdown all my blogs






09-30
  call
    joliet
    obriens
  
  errands
    bike <= stavi
    1TB @microcenter

09-25
  write component for video embed, yt
  # alias nvim

  hit up @renzo about xampp and php

  # syslink nvim dotfiles

  # cleanup repo /dotfiles master branch
  # renamed old repo, created new
  # still need to
  fixup old dotfiles repo, integrate new
